/**
 * NOTE: This class is auto generated by the swagger code generator program (unset).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Author;
import java.util.List;
import javax.annotation.Generated;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-09-24T19:22:52.557+08:00")

@Api(value = "author", description = "the author API")
public interface AuthorApi {

  @ApiOperation(value = "Get the information of an author by id", notes = "", response = Author.class, tags = {
      "author",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "successful operation", response = Author.class),
      @ApiResponse(code = 404, message = "Author not found", response = Void.class)})

  @RequestMapping(value = "/author/{id}",
      produces = {"application/json"},
      method = RequestMethod.GET)
  ResponseEntity<Author> getAuthorById(
      @ApiParam(value = "id of the author", required = true) @PathVariable("id") String id);


  @ApiOperation(value = "Get all author ids", notes = "Returns a list of author ids with specified criteria", response = String.class, responseContainer = "List", tags = {
      "author",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "successful operation", response = String.class, responseContainer = "List")})

  @RequestMapping(value = "/author",
      produces = {"application/json"},
      method = RequestMethod.GET)
  ResponseEntity<List<String>> getAuthors();

}
