/**
 * NOTE: This class is auto generated by the swagger code generator program (unset).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Paper;
import java.util.List;
import javax.annotation.Generated;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-09-24T19:22:52.557+08:00")

@Api(value = "paper", description = "the paper API")
public interface PaperApi {

  @ApiOperation(value = "Get the paper specified by id", notes = "", response = Paper.class, tags = {
      "paper",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "successful operation", response = Paper.class)})

  @RequestMapping(value = "/paper/{id}",
      produces = {"application/json"},
      method = RequestMethod.GET)
  ResponseEntity<Paper> getPaperById(
      @ApiParam(value = "ID of the paper", required = true) @PathVariable("id") String id);


  @ApiOperation(value = "Get all papers (cited or base papers)", notes = "Find papers with given filters", response = String.class, responseContainer = "List", tags = {
      "paper",})
  @ApiResponses(value = {
      @ApiResponse(code = 200, message = "successful operation", response = String.class, responseContainer = "List")})

  @RequestMapping(value = "/paper",
      produces = {"application/json"},
      method = RequestMethod.GET)
  ResponseEntity<List<String>> getPapers(
      @ApiParam(value = "Name of the author of papers") @RequestParam(value = "author", required = false) String author,
      @ApiParam(value = "Year of the paper published") @RequestParam(value = "year", required = false) Integer year);

}
